# Site settings
title: Nova Angular
email: hicham.elhammouchi@gmail.com
url: http://www.novaangular.com
description: "Nova Angular Meetup Website"
version: 0.0.1
hostName: www.novaangular.com
domainName: novaangular.com
meetupUrl: https://www.meetup.com/Nova-Angular/
joinMeetupUrl: https://www.meetup.com/Nova-Angular/join/
slackUserName: hicham
slackInviteUrl: https://join.slack.com/novaangular/shared_invite/MjEyMTQzMDkzNjA3LTE0OTk4MDM5NjgtMmQ5NjVkOGRhOA

# Build settings
markdown: kramdown
permalink: pretty
kramdown:
  toc_levels: '2,3'